### ISSUE TITLE
Add library to JamVM Classpath

### ISSUE THREAD

**Issue by merdes** [cfriedt/jamvm#1]
I need to use JamVM for performance reasons but now i'm having the problem when i invoke my jar using the option `-jamvm` does not found a library .

I tried adding the option:
`-classpath ".:sqlite-jdbc-3.8.7.jar"`

It does not work either i get the exception:
`java.lang.ClassNotFoundException: org.sqlite.JDBC`

If i use the OpenJDK JVM works fine.

Any idea?

**Comment by cfriedt** [comment]
Likely you have not compiled it with zlib support. Doing so may require that you download zlib-devel our zlib source and compile / build / install that first. A jar is just a zip file, but JamVM requires zlib to open it. In any case, I would first suggest you search Google for a similar error message, and if either of the two preceding solutions does not work, I would suggest you post something on the [JamVM mailing list](https://lists.sourceforge.net/lists/listinfo/jamvm-general)

Also, read the command-line help items. There are extra options for classloader debugging that you likely have not even seen.
